In [6]:
import numpy as np

list = [10, 20, 30]

print(type(list))

ar1 = np.array(list)

print(type(ar1))

ar2 = np.array([10, 20, 30])
print(type(ar2))
print(ar2)

ar3 = np.array([[10, 20, 30], [40, 50, 60]])
print(type(ar3))
print(ar3)


<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[10 20 30]
<class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]
